<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Project</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="container">
            <h1>Project</h1>
            <h2>User form</h2>
            <div class="user-form row">
                <?php 
                    echo $this->fetch('register-form.phtml', ['errors' => null]);
                ?>
            </div>
        </div>
    </body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $(document).on("submit", "form", function (e) {
            e.preventDefault();

            var data = $(this).serialize();
            var file = $('#profile_picture')[0].files;
            var countryCode = $('select option:selected').attr('data-country-code');
            var form = $(this)[0];
            var formData = new FormData(form);
            formData.append('profile_picture', file);
            formData.append('country_code', countryCode);

            $.ajax({
                type: "POST",
                url: '/',
                data: formData,
                contentType: false,
                processData: false,
                success: function(data) {
                    $('.user-form').html(data.form);
                    
                    if (data.success) {
                        // ALL GOOD! just show the success message!
                        $('form').prepend('<div class="alert alert-success">' + data.message + '</div>');
                    } else {
                        // Error! Failed to register user to database
                        $('form').prepend('<div class="alert alert-danger">' + data.message + '</div>');
                    }
                },
                error: function(err) {
                    // Error! Failed to register user to database
                    $('form').prepend('<div class="alert alert-danger">' + err + '</div>');
                }
            });
        });
    });
</script>
